"db": {
    "comment": [{
        "comment": String,
        "commentId": String,
        "createdAt": TimeStamp,
        "ipv6": String,
        "isNFTicon": false,
        "isOfficial": false,
        "likesUids": [ String ],
        "likesUidsCount": int,
        "negativeScore": int,
        "positiveScore": int,
        "postId": string,
        "score": int,
        "uid": String,
        "userDocId": String,
        "userName": String,
        "userImageURL": String,
    }],
    "nftOwners"{
        "ethPrice": int,
        "link": String,
        "userName"; String,
        "number": int,
        "uid": uid,
        "userImageURL": String,
    }
    "posts"{
        "audioURL": String,
        "bookmarks": [{
            "createdAt": TimeStamp,
            "uid": String,
        }],
        "bookmarksCount": int,
        "commentsState": String('open','isLocked','onlyFollowingUsers'),
        "createdAt": TimeStamp,
        "country": string,
        "genre": String,
        imageURL: String,
        impression: int,
        ipv6: String,
        isNFTicon: bool,
        isOfficial: bool,
        isPlayedCount: int,
        likes: [{
            createdAt: TimeStamp,
            uid: String,
        }],
        likesCount: int,
        link: String,
        noDisplayWords: list,
        noDisplayUids: list,
        negativeScore: int,
        postId: String,
        positiveScore: 0,
        score: int,
        title: String,
        uid: String,
        updatedAt: TimeStamp,
        userDocId: String,
        userImageURL: String,
        userName: String
    }
    replys{
        elementId: String,
        elementState: string [ comment ],
        createdAt: TimeStamp,
        ipv6: String,
        isNFTicon: bool,
        isOfficial: bool,
        likesUids: [],
        likesUidsCount: int,
        negativeScore: int,
        positiveScore: int,
        reply: String,
        replyId: String,
        score: int,
        uid: String,
        userDocId: String,
        userName: String,
        userImageURL: String,
    }
    users{
        birthDay: TimeStamp,
        blockingUids: [ String ],
        bookmarks: [{
            createdAt: TimeStamp,
            postId: String,
        }],
        commentNotifications: [{
            'comment': String,
            'createdAt': TimeStamp,
            'isNFTicon': bool,
            'isOfficial':bool,
            'notificationId': String,
            'notificationId': notificationId,
            'postTitle': String,
            'uid': String,
            'userDocId': String,
            'userName': String,
            'userImageURL': String,
        }],
        createdAt: TimeStamp,
        description: String,
        dmState: ["onlyFollowingAndFollowed","open"],
        followNotifications: [],
        followersCount: int,
        followerUids:[
            String
        ],
        followingUids: [
            String
        ],
        gender: String[male,female,others,noAnswer],
        imageURL: String,
        isAdmin: bool,
        isNFTicon: bool,
        isKeyAccount: bool,
        isOfficial: bool,
        isSubAdmin: bool,
        subscriptions: List<Map<String,dynamic>{
            'subscriptionId': String,
            'planName': String,
        }>,
        joiningGroups: List<Map<String,dynamic> {
            'groupName': String,
            'groupId': String,
        }>,
        language: String ja,en,
        likedComments:[{
            commentId: String,
            createdAt: TimeStamp,
        }],
        likeNotifications: [],
        likedReplys: [{
            'createdAt': TimeStamp,
            'likedReplyId': String,
        }],
        likes: [{
            createdAt: TimeStamp,
            likedPostId: String,
        }],
        link: String,
        mutesReplyIds: List<String>,
        mutesUids: List<String>,
        mutesCommentIds: List<String>,
        mutesIpv6AndUids: List<Map<String,dynamic>>{
            'ipv6': String,
            'uid': String,
        },
        mutesPostIds: List<String>,
        noDisplayWordsOfComments: List<String>,
        noDisplayWordsOfMyPost: List<String>,
        otherLinks: List<Map<String,dynamic>{
            'description': String,
            'link': String,
        }>,
        readNotificationIds: [ String ],
        readPosts: [{
            'createdAt': TimeStamp,
            'durationInt': int,
            'postId': String,
        }],
        recommendState: 'recommendable',
        replyNotifications: [{
            comment: String,
            elementId: String,
            createdAt: TimeStamp,
            'isNFTicon': bool,
            'isOfficial':bool,
            notificationId: String,
            reply: String,
            uid: String,
            userDocId: String,
            userName: String,
            userImageURL: String,
        }],
        score: int,
        searchHistorys: List<String>,
        subUserName: String,
        uid: String,
        updatedAt: String,
        userName: String,
        walletAddress: String,
    }

    watchLists {
        creatorUid: String,
        uids: [ String ],
        label: String ,
        watchListId: String,
        createdAt: TimeStamp,
        updatedAt: TimeStamp,
    }
    bookmarkLabels {
        creatorUid: String,
        postIds: [ String ],
        label: String,
        bookmarkLabelId: String,
        createdAt: TimeStamp,
        updatedAt: TimeStamp,
    }
}