name: whisper
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^0.14.0+3
  firebase_core: ^1.6.0
  firebase_auth: ^3.1.0
  cloud_firestore: ^2.5.1
  firebase_analytics: ^8.3.1
  google_fonts: ^2.1.0
  firebase_storage: ^10.0.3
  path_provider: ^2.0.2
  just_audio: ^0.9.7
  pull_to_refresh: ^2.0.0
  audio_video_progress_bar: ^0.9.0
  image_picker: ^0.8.3+3
  flutter_svg: ^0.22.0
  dotenv: ^3.0.0
  flutter_dotenv: ^5.0.2
  algolia: ^1.0.1
  record: ^3.0.0
  top_snackbar_flutter: ^1.0.0
  stop_watch_timer: ^1.3.1
  image_cropper: ^1.4.1
  shared_preferences: ^2.0.8
  flutter_slidable: ^0.6.0
  dart_ipify: ^1.1.1
  marquee: ^2.2.0
  url_launcher: ^6.0.12
  clipboard: ^0.1.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/svgs/
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
