name: whisper
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+13

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.3
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.11
  cloud_firestore: ^3.1.10
  firebase_analytics: ^9.1.2
  google_fonts: ^2.1.0
  pull_to_refresh: ^2.0.0
  stop_watch_timer: ^1.3.1
  image_cropper: ^1.4.1
  shared_preferences: ^2.0.13
  flutter_slidable: ^0.6.0
  url_launcher: ^6.0.20
  clipboard: ^0.1.3
  flutter_launcher_icons: ^0.9.2
  flash: ^2.0.3+1
  freezed_annotation: ^0.14.3
  json_serializable: ^6.1.3
  uuid: ^3.0.5
  dart_ipify: ^1.1.1
  record: ^3.0.2
  image_picker: ^0.8.4+11
  just_audio: ^0.9.18
  flutter_svg: ^1.0.3
  audio_video_progress_bar: ^0.10.0
  firebase_storage: ^10.2.9
  firebase_crashlytics: ^2.5.3
  fluttertoast: ^8.0.9


dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/official_logo.jpeg'


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/svgs/
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
