// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'post.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Post _$PostFromJson(Map<String, dynamic> json) => Post(
      accountName: json['accountName'] as String,
      audioURL: json['audioURL'] as String,
      bookmarks: json['bookmarks'] as List<dynamic>,
      bookmarkCount: json['bookmarkCount'] as int,
      commentCount: json['commentCount'] as int,
      commentsState: json['commentsState'] as String,
      country: json['country'] as String,
      description: json['description'] as String,
      genre: json['genre'] as String,
      hashTags: json['hashTags'] as List<dynamic>,
      imageURL: json['imageURL'] as String,
      impression: json['impression'] as int,
      ipv6: json['ipv6'] as String,
      isDelete: json['isDelete'] as bool,
      isNFTicon: json['isNFTicon'] as bool,
      isOfficial: json['isOfficial'] as bool,
      isPinned: json['isPinned'] as bool,
      likes: json['likes'] as List<dynamic>,
      likeCount: json['likeCount'] as int,
      link: json['link'] as String,
      noDisplayWords: json['noDisplayWords'] as List<dynamic>,
      noDisplayIpv6AndUids: json['noDisplayIpv6AndUids'] as List<dynamic>,
      negativeScore: json['negativeScore'] as int,
      otherLinks: json['otherLinks'] as List<dynamic>,
      playCount: json['playCount'] as int,
      postId: json['postId'] as String,
      positiveScore: (json['positiveScore'] as num).toDouble(),
      score: (json['score'] as num).toDouble(),
      storageImageName: json['storageImageName'] as String,
      storagePostName: json['storagePostName'] as String,
      tagUids: json['tagUids'] as List<dynamic>,
      title: json['title'] as String,
      tokenToSearch: json['tokenToSearch'] as Map<String, dynamic>,
      uid: json['uid'] as String,
      userImageURL: json['userImageURL'] as String,
      userName: json['userName'] as String,
    );

Map<String, dynamic> _$PostToJson(Post instance) => <String, dynamic>{
      'accountName': instance.accountName,
      'audioURL': instance.audioURL,
      'bookmarks': instance.bookmarks,
      'bookmarkCount': instance.bookmarkCount,
      'commentCount': instance.commentCount,
      'commentsState': instance.commentsState,
      'country': instance.country,
      'description': instance.description,
      'genre': instance.genre,
      'hashTags': instance.hashTags,
      'imageURL': instance.imageURL,
      'impression': instance.impression,
      'ipv6': instance.ipv6,
      'isDelete': instance.isDelete,
      'isNFTicon': instance.isNFTicon,
      'isOfficial': instance.isOfficial,
      'isPinned': instance.isPinned,
      'likes': instance.likes,
      'likeCount': instance.likeCount,
      'link': instance.link,
      'noDisplayWords': instance.noDisplayWords,
      'noDisplayIpv6AndUids': instance.noDisplayIpv6AndUids,
      'negativeScore': instance.negativeScore,
      'otherLinks': instance.otherLinks,
      'playCount': instance.playCount,
      'postId': instance.postId,
      'positiveScore': instance.positiveScore,
      'score': instance.score,
      'storageImageName': instance.storageImageName,
      'storagePostName': instance.storagePostName,
      'tagUids': instance.tagUids,
      'tokenToSearch': instance.tokenToSearch,
      'title': instance.title,
      'uid': instance.uid,
      'userImageURL': instance.userImageURL,
      'userName': instance.userName,
    };
