const int verifyMailIntervalSeconds = 5;
const int oneTimeReadCount = 30;
// const int defaultScore = 10000;// (lib/posts/components/replys/replys_model.dart, lib/posts/components/comments/comments_model.dart, lib/components/add_post/add_post_model.dart)
const int topFlashDisplaySeconds = 4;
const int commentScrollFlashBarConstantCount = 2;
const int dialogueMilliSeconds = 500;
const int maxLine = 2;
const int plusOne = 1;
const int minusOne = -1;